### ISSUE TITLE
Saving only elements of the ontology used by the individuals

### ISSUE THREAD

**Issue by versae** [pwin/owlready2#1]
Hi, thanks for this library!

I was trying to create some individuals for a fairly large ontology, but after running `onto.save(file = "output.n3", format = "ntriples")` I see that the entire ontology is also in the saved file. Is there a way to only dump the elements that are actually used by the individuals?

Cheers.

**Comment by pwin** [comment]
hi @versae 
This is a great library, but it isn't mine - it is a fork from the bitbucket repo to git.  The readme has all the information, but the specific chunk at the end of the readme gives you the link to the author (Jiba) and the mailing list.  Perhaps you can ask your question there so that it is all together

Owlready2 on BitBucket (development repository): https://bitbucket.org/jibalamy/owlready2

Owlready2 on PyPI (Python Package Index, stable release): https://pypi.python.org/pypi/Owlready2

Documentation: http://owlready2.readthedocs.io/

Forum/Mailing list: http://owlready.8326.n8.nabble.com

Contact "Jiba" Jean-Baptiste Lamy:

<jean-baptiste.lamy *@* univ-paris13 *.* fr>
LIMICS
University Paris 13, Sorbonne Paris Cite
Bureau 149
74 rue Marcel Cachin
93017 BOBIGNY
FRANCE

**Comment by versae** [comment]
Thanks!
